name: build-CI-pipeline

on:
  workflow_dispatch:

jobs:
  Build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: change file permission
        run: chmod +x test.sh

      - name: Run the script
        run: ./test.sh

      - name: Check script behaviour
        env:
          FAIL_PIPELINE: false
        run: ./test.sh
