name: Hello workflow
on:
  push: 

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4 #Action to clone repo

      - name: Print Hello
        run: echo "Hello from GitHub Actions" 