name: Hello workflow
on:
  push: 

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code 
        uses: actions/checkout@v4 #Action to clone repo

      - name: Print Hello
        run: echo "Hello from GitHub Actions" 
      
      - name: Set current date
        run: echo "NOW=$(date + '%Y-%m-%d%H:%M:%S')" 

      - name: Print current date and time
        run: echo "The current time is $NOW"
        