name: Ignore Docs Only Changes

on:
  push:
    branches:
      - main
      - "release/*"
    paths-ignore:
      - "*.md"
      - "docs/**"

jobs:
  run-unless-docs-only:
    runs-on: ubuntu-latest

    steps:
      - name: Run when non-doc files change
        run: echo "Non-doc changes detected"
