name: Multi-Job-Dependency

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/chekout@v4

      - name: Builing the app
        run: echo "Building the app"

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Running the test
        run: echo "Running tests"

  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Running the test
        run: echo "Deploying"
