name: read-secrets

on:
  workflow_dispatch:

jobs:
  Read-secret-and-print:
    runs-on: ubuntu-latest

    steps:
      - name: Read secret & print
        run: echo "My secret is ${{ secrets.MY_SECRET_MESSAGE }}"
