name: read-secrets

on:
  workflow_dispatch:

jobs:
  Read_secret and print:
    runs-on: ubuntu-latest

    steps:
      - name: Read secret and print
        run: echo "My secret is ${{ secrets.MY_SECRET_MESSAGE }}"
