name: read-secrets

on:
  push:

jobs:
  Read_secret and print:
    runs-on: ubuntu-latest

    steps:
      - name: read the secret and print it
        run: echo "My secret is ${{ secrets.MY_SECRET_MESSAGE }}"
