name: reusable-actions
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment: # Key name for the input
        description: "Environment to run against"
        required: true
        default: "staging"
        type: string
    secrets:
      docker_token:
        required: true

jobs:
  reusable-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Building app for environment
        run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"

      - name: Check if the token exists
        env:
          DOCKER_TOKEN: ${{ secrets.docker_token }}
        run: |
          if [-n "$DOCKER_TOKEN" ];then
           echo "Docker token is set: true"
          else
           echo "Docker token is set:false"
          fi
