name: Step-Configuration

on:
  push:
  pull_request:

jobs:
  Main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Run when branch is Main
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        run: echo "This is step 1 from main branch"

      - name: Run when only previous step is failed
        #if: always()
        run: echo "This step runs always"

  Run-on-PE:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Run on push event only
        run: echo "This only runs on direct pushes, not PRs"
