name: Step-Configuration

on:
  push:
  pull_request: # by default it will run on push and pull requests

jobs:
  Main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Run when branch is Main
        if: github.ref == 'refs/heads/main' # condition that it should only run when the branch is main
        continue-on-error: true. # even if this step fails actions should continue to next step
        run: echo "This is step 1 from main branch"

      - name: Run when only previous step is failed
        #if: always()
        run: echo "This step runs always"

  Run-on-PE:
    if: github.event_name == 'push'. # run the job only if it is a pull request
    runs-on: ubuntu-latest

    steps:
      - name: Run on push event only
        run: echo "This only runs on direct pushes, not PRs"
