name: upload-artifacts

on:
  workflow_dispatch:

jobs:
  create-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Generate report
        run: echo "Report content" > report.txt # writes to report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: my-report
          path: report.txt
